import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'

import Head from 'next/head'
import Link from 'next/link'

import { Box, Container, Flex } from '@repo/ui'

import ClientProviders from './providers/client.providers'
import { Logo } from './shared/Logo.component'
import { Menu } from './shared/Menu.component'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head>
        <Link
          rel="preload"
          href="/background.jpg"
          as="image"
          prefetch
        />
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ background: "url('/background.jpg')" }}
      >
        <ClientProviders>
          <Container
            maxW="980px"
            mt="2em"
          >
            <Logo />

            <Flex
              justifyContent="space-between"
              alignItems="stretch"
            >
              <Box
                flexGrow="1"
                maxWidth="150px"
              >
                <Menu />
              </Box>

              <Box flexGrow="5">{children}</Box>
            </Flex>
          </Container>
        </ClientProviders>
      </body>
    </html>
  )
}
